---
title: "DATA-413/613 HW 01"
author: "Your Name"
date: "`r Sys.Date()`"
output:
  html_document: 
    number_sections: true
---

# Instructions {-}
Complete both the Admin elements and the Analysis Elements of this assignment.

# Canvas Picture, Syllabus, and Student Info
Review the Syllabus on Canvas and answer the following questions:

I, *enter your name*  have:

1. Ensured my Canvas Profile has a photo of me (head and shoulders)

2. Reviewed the syllabus and the associated policies on the following date: ___fill in the date__________

3. Reviewed the American University policies on academic integrity and agree to comply with them and the additional guidance in the syllabus for this course

4. Confirmed my information in the Student Info spreadsheet on Canvas collaborations is correct.

# College Scorecard

The data folder contains "college_scorecard_extract_ 2021-08-03.csv", a subset of the data in the [College Scorecard](https://collegescorecard.ed.gov/data/) database as of August 03, 2021. These data contain information on college cohorts in the United States. The variables include:

- `UNITID` and `OPEID`: Identifiers for the colleges.
- `INSTNM`: Institution name
- `ADM_RATE`: The Admission Rate.
- `SAT_AVE`: Average SAT equivalent score of students admitted.
- `UGDS`: Enrollment of undergraduate certificate/degree-seeking students
- `COSTT4_A`: Average cost of attendance (academic year institutions)
- `AVGFACSAL`: Average faculty salary
- `GRAD_DEBT_MDN`: The median debt for students who have completed
- `AGE_ENTRY`: Average age of entry
- `ICLEVEL`: Level of institution (1 = 4-year, 2 = 2-year, 3 = less than 2-year).
- `MN_EARN_WNE_P10`: Mean earnings of students working and not enrolled 10 years after entry.
- `MD_EARN_WNE_P10`: Median earnings of students working and not enrolled 10 years after entry.
- `FEMALE`: Share of female students
- `PCT_WHITE`: Percent of the population from students' zip codes that is White, via Census data

1. Use a relative path and a {readr} function to load the data from data/college_scorecard_extract_2021-08-03.csv into a tibble. Note, this data uses NULL instead of `NA` so convert NULL to `NA` while reading in. Do not not suppress messages or warnings.
   
2. If you used the default settings for reading in the data, multiple variables are probably type character when they should be numeric. 
  + Which ones? 
  + Why were they read in as type character? 

3. Reload the data with a {readr} function and use an argument so the variables are read in as numeric.

4. How is average faculty salary associated with the average earnings of students ten years after initial enrollment? 

  - State the question you are trying to answer based on your choice of response and explanatory variables. 
  - Create an appropriate plot to assess for a relationship.
  - Use a {ggplot2} function to reduce overplotting.
  - Use the default smoother. Explain why ggplot2 chose the method.
  - Interpret the plot to answer your question. 

5. Does the level of the institution seem to be associated with the median earnings of students ten years after enrollment? 

  - Reproduce this plot in R to explore this relationship 
  - Interpret the plot

6. Plot the median earnings 10 years after enrollment for level 1 institutions as the Y axis against PCT_WHITE and, in a second plot, against FEMALE.  

  - Use a log scale as appropriate.
  - Add a loess smoother. 
  - Describe and interpret the non-linear relationship in each of the plots.

7. Create a scatter plot of the mean earnings 10 years after enrollment (Y axis) compared to the median earnings 10 years after enrollment (X axis) using log scales for both.  
  + Add a 45 degree abline. 
  + Use color to differentiate the level of institutions and attempt to reduce effects of overplotting.
  + Interpret the plot and the relationship between the two variables considering the abline.

8. Use a {dplyr} function to compute a ranking of level 1 universities based on the ratio of median earnings 10 years after enrollment compared to median graduation debt for those schools that have both data elements. Break any ties using the minimum value such that if two schools are tied for 4th, they are each ranked 4 and the next school is 6.
  + Identify the top 5 best (highest ROI should be #1 ) and the bottom 5 worst. Show only their rank, name, ROI, cost, debt, and earnings. 
  + What is American University's rank and ROI? Show only the rank, name, ROI, cost, debt, and earnings? 

- Extra Credit: 
  + Reproduce the following plot so the *AU line and number of institutions automatically adjusts as new data is entered*:
  + What is AU's new ranking and ROI if the mean earnings are used?

# World Bank Data

The World Bank provides loans to countries with the goal of reducing poverty. The dataframes in the data folder were taken from the public data repositories of the World Bank.

- `country.csv`: Contains information on the countries in the data set. The variables are:
  - `Country_Code`: A three-letter code for the country. Note not all rows are countries; some are regions.
  - `Region`: The region of the country.
  - `IncomeGroup`: Either `"High income"`, `"Upper middle income"`, `"Lower middle income"`, or `"Low income"`.
  - `TableName`: The full name of the country.  

- `fertility.csv`: Contains the fertility rate information for each country for each year. 
  + For the variables `1960` to `2017`, the values in the cells represent the fertility rate in total births per woman for that year. 
  + Total fertility rate represents the number of children that would be born to a woman if she were to live to the end of her  childbearing years and bear children in accordance with age-specific fertility rates of the specified year.   

- `life_exp.csv`: Contains the life expectancy information for each country for each year. 
  + For the variables `1960` to `2017`, the values in the cells represent life expectancy at birth in years for the given year. 
  + Life expectancy at birth indicates the number of years a newborn infant would live if prevailing patterns of mortality at the time of its birth were to stay the same throughout its life.  

- `population.csv`: Contains the population information for each country. 
  + For the variables `1960` to `2017`, the values in the cells represent the total population in number of people for the given year. 
  + Total population is based on the de facto definition of population, which counts all residents regardless of legal status or citizenship. The values shown are mid-year estimates.

1. Use relative paths and a readr function to load these files into four tibbles.  

2. These data are messy. The observational units in `fert`, `life`, and `pop` are locations in space-time (e.g. Aruba in 2017). Recall tidy data should have one observational unit per row.  
  - Use {tidyr} functions to tidy these three tibbles and save the updated data frames.
  - Use an argument so the {tidyr} function ensures the variable for `year` is a numeric.  

3. Use {dplyr} functions to join the three tibbles into one and save to a new tibble which includes the fertility rate, population, and life expectancy in each year as well as the region for each country.

4. Make a scatterplot of fertility rate vs life expectancy, color-coding by region and annotating size by the population.  
  + Include only the years 1960, 1970, 1980, 1990, 2000, and 2010. 
  + Facet by these years.
  + Your final plot should look like this (Each element of the formatting is graded):
  + **Interpret the plot in one sentence**.

5. Calculate the total population for each region for each year.  
  + Exclude 2018.  
  + Make a line plot of year versus total population, color-coding by region and using a log scale.
  + Your final plot should look like this:
  + **Interpret the plot in one sentence to identify the two fastest growing regions**.

6. Make a box plot of percentage population growth vs region between 1960 and 2010.  
  + Order the Regions on the $y$-axis in **increasing** order of total 1960 population. 
  + For any countries with negative growth set to .001.
  + Add a red line at 100%
  + Your final plot should look like this:
  + **Interpret the plot in one sentence to compare the percentage growth with the previous plot.**
