---
title: "STAT 413/613 HW 1"
subtitle: ""
author: "YOUR NAME"
date: "`r Sys.Date()`"
output:
  html_document: 
    number_sections: true
editor_options:
  chunk_output_type: inline
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align  = "center",
                      fig.height = 4, 
                      fig.width  = 6)
```

# Instructions

- Write your solutions in this starter file. You should modify the 
  "author" field in the YAML header.
- Only commit R Markdown and HTML files (no PDF files). Make sure
  you have knitted to HTML for your final submission.
- **Committing each time you answer a question is a graded element for this homework.**
- Only include necessary code, not any extraneous code, to answer the 
  questions.
- Most of the functions you use should be from the tidyverse. Too much
  much base R will result in point deductions.

# Learning outcomes:  
- Operate with Git and GitHub.
- Apply concepts and methods from STAT 412/612.   

# World Bank Data

The World Bank is an international organization that
provides loans to countries with the goal of reducing poverty. The 
data frames in the data folder were all taken from the public data 
repositories of the World Bank.

- country.csv: 
  Contains information on the countries in the data set. The
  variables are:
    - `Country_Code`: A three-letter code for the country. Note that not all
      rows are countries; some are regions.
    - `Region`: The region of the country.
    - `IncomeGroup`: Either `"High income"`, `"Upper middle income"`, 
      `"Lower middle income"`, or `"Low income"`.
    - `TableName`: The full name of the country.
- fertility.csv: 
  Contains the fertility rate information for each country
  for each year. For the variables `1960` to `2017`, the values in the cells
  represent the fertility rate in total births per woman for the that year. 
  Total fertility rate represents the number of children 
  that would be born to a woman if she were to live to the end of her 
  childbearing years and bear children in accordance with age-specific 
  fertility rates of the specified year.
- life_exp.csv: 
  Contains the life expectancy information for each country 
  for each year. For the variables `1960` to `2017`, the values in the cells
  represent life expectancy at birth in years for the given year. 
  Life expectancy at birth indicates the number of years a newborn 
  infant would live if prevailing patterns of mortality at the time of its
  birth were to stay the same throughout its life.
- population.csv: 
  Contains the population information for each country. For
  the variables `1960` to `2017`, the values in the cells represent the total
  population in number of people for the given year. 
  Total population is based on the de facto definition of
  population, which counts all residents regardless of legal status or 
  citizenship. The values shown are midyear estimates.

1. Use relative paths to load these data frames into R.

    
2. These data are messy. The observational units in `fert`, `life`, and `pop`
   are locations in space-time (e.g. Aruba in 2017). Recall that tidy data
   should have one observational unit per row. Make these data tidy now.
   Make sure that the new year variable is a numeric.

    
3. Combine these data frames so that we have the fertility rate, population,
   life expectancy, and the region for each country in each year in a single
   data frame.
    
4. Make a scatterplot of fertility rate vs life expectancy, color-coding by
   region and annotating the size by the the population. Do this for
   the years 1960, 1970, 1980, 1990, 2000, and 2010. Facet by these years.
   Make your plot aesthetically pleasing.
   Your final plot should look like this:

   
5. Calculate the total population for each region for each year. Exclude 2018.  Make a line plot of year versus total population, color-coding by region. Your final plot should look like this:
   
    
6. Make a bar plot of population vs region for the year 2017. Order the
   bars on the $y$-axis in **decreasing** order of population. Your final 
   plot should look like this:
   
# Scrabble Words

For this exercise, we are using the 
[Collins Scrabble Words](https://en.wikipedia.org/wiki/Collins_Scrabble_Words), which is most commonly used outside of the United States. The dictionary most often used in the United States is the [Tournament Word List](https://en.wikipedia.org/wiki/Official_Tournament_and_Club_Word_List).

**WARNING**: Do not try `str_view()` or `str_view_all()` on these data.
It will stall your computer.

1. Load the 2015 list of Collins Scrabble Words into R from 
   <https://data-science-master.github.io/lectures/data/words.txt>
   (note: "NA" is an official Scrabble word).
 
   
2. What are the four shortest word that have the most "Z"'s in them?


3. How many words have an identical first and second half of the word? For words with an odd number of characters, exclude the middle character from consideration. For example, "JIGAJIG" counts because "JIG" is both the first and second half. "MURMUR" also counts because "MUR" is both the first and  second half.
    
4. What is the longest word that has an identical first and second half
   of the word?
   
    
# Conceptual Exercises

1. What are the appropriate plots for ...  
    1. Exploring the association between two quantitative variables?
    
    2. Exploring the association between a quantitative and a categorical variable?
    
    3. Looking at the distribution of a quantitative variable? 
    
    4. Looking at the distribution of a categorical variable?   
 
2. In each of the following scenarios:  
    + What are the observational/experimental units?
    + Classify each variable as quantitative or categorical.       


1. In 1899, biologist Hermon Bumpus collected data on the moribund house sparrow after a severe winter. For each sparrow, he measured the humerus (arm bone) length in inches, as well as whether or not the sparrow survived the winter. He was interested in whether humerus length was associated with survival.

2. In 1995, the National Highway System Designation Act allowed states to set their own speed limits, as opposed to the previously federally-mandated speed limit of 55-miles-per-hour. Thirty-two states elected to increase their speed limits. Researchers collected the percent change in traffic fatalities for all states. They were interested in whether states that increased their speed limit also experienced an increase in traffic fatalities.  
       











